# Generated by Django 5.0.3 on 2024-03-21 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format  (\\+98|0)?9\\d{9}$', regex='^(\\+98|0)?9\\d{9}$')])),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('is_admin', models.BooleanField(blank=True, default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(blank=True, default=False)),
                ('otp', models.CharField(blank=True, max_length=6)),
                ('otp_expire_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
