# Generated by Django 5.0.6 on 2024-07-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='change_address_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
