# Generated by Django 5.0.7 on 2024-07-25 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customer_address_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='city',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='owner_address',
        ),
    ]
