# Generated by Django 5.0.7 on 2024-08-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_owner_city_remove_owner_owner_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='score',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
