# Generated by Django 5.0.3 on 2024-03-27 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_food_restaurant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='foodcategory',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='core.foodcategory'),
        ),
        migrations.RemoveField(
            model_name='foodcategory',
            name='menu',
        ),
    ]
