# Generated by Django 5.0.7 on 2024-07-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_food_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
