# Generated by Django 5.0.3 on 2024-03-25 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_restaurant_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='cofe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favcofe', to='core.cofe'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favres', to='core.restaurant'),
        ),
    ]
