# Generated by Django 5.0.3 on 2024-03-27 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_foodcategory_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodcategory',
            name='category_desc',
        ),
    ]
