# Generated by Django 5.0.3 on 2024-03-25 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_favorite_cofe_alter_favorite_restaurant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='cofe',
        ),
        migrations.RemoveField(
            model_name='cofefood',
            name='cofe',
        ),
        migrations.RemoveField(
            model_name='cofefood',
            name='food_category',
        ),
        migrations.RemoveField(
            model_name='restaurantfood',
            name='food_category',
        ),
        migrations.RemoveField(
            model_name='restaurantfood',
            name='restaurant',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='core.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('name', models.CharField(max_length=150)),
                ('desc', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('food_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='core.foodcategory')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resfoods', to='core.restaurant')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='core.menu')),
            ],
        ),
        migrations.DeleteModel(
            name='Cofe',
        ),
        migrations.DeleteModel(
            name='CofeFood',
        ),
        migrations.DeleteModel(
            name='RestaurantFood',
        ),
    ]
