# Generated by Django 5.0.3 on 2024-03-27 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_foodcategory_category_desc'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='foodcategory',
            unique_together={('category_name',)},
        ),
    ]
