# Generated by Django 5.0.3 on 2024-03-27 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_foodcategory_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategory',
            name='restaurant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='food_categories', to='core.restaurant'),
        ),
        migrations.AlterField(
            model_name='food',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_foods', to='core.menu'),
        ),
    ]
