# Generated by Django 5.0.3 on 2024-03-27 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_foodcategory_restaurant_alter_food_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_categories', to='core.restaurant'),
        ),
    ]
