# Generated by Django 5.0.3 on 2024-03-27 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_foodcategory_restaurant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='foodcategory',
            unique_together={('category_name', 'restaurant')},
        ),
    ]
