# Generated by Django 5.0.7 on 2024-08-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_restaurant_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='average_rating',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='average_rating',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
