# Generated by Django 5.0.3 on 2024-03-28 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_foodcategory_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='foodcategory',
            unique_together={('category_name',)},
        ),
        migrations.RemoveField(
            model_name='foodcategory',
            name='restaurant',
        ),
    ]
