# Generated by Django 5.0.3 on 2024-03-28 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_foodcategory_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='description',
        ),
    ]
