# Generated by Django 5.0.3 on 2024-03-28 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_menu_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='category_name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='FoodCategoryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=255)),
                ('cat_desc', models.TextField(blank=True)),
                ('admin_approval', models.BooleanField(default=False)),
                ('restaurant', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_request', to='core.restaurant')),
            ],
        ),
    ]
