# Generated by Django 5.0.3 on 2024-03-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_foodcategory_category_name_foodcategoryrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategoryrequest',
            name='admin_approval',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
