# Generated by Django 5.0.3 on 2024-03-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_foodcategoryrequest_admin_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategoryrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
