# Generated by Django 5.0.3 on 2024-03-27 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_name', models.CharField(default='', max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('user', models.ManyToManyField(related_name='address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
