# Generated by Django 5.0.6 on 2024-07-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_restaurantrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='stars',
            field=models.PositiveSmallIntegerField(choices=[(1, '1Stars'), (2, '2Stars'), (3, '3Stars'), (4, '4Stars'), (5, '5Stars')]),
        ),
        migrations.AlterField(
            model_name='restaurantrating',
            name='stars',
            field=models.PositiveSmallIntegerField(choices=[(1, '1Stars'), (2, '2Stars'), (3, '3Stars'), (4, '4Stars'), (5, '5Stars')]),
        ),
    ]
