# Generated by Django 5.0.7 on 2024-07-17 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_user_change_address_time'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='account.customer')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='core.restaurant')),
            ],
            options={
                'unique_together': {('customer', 'restaurant')},
            },
        ),
        migrations.CreateModel(
            name='Restaurant_cart_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.food')),
                ('restaurant_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='cart.restaurant_cart')),
            ],
            options={
                'unique_together': {('restaurant_cart', 'food')},
            },
        ),
    ]
