# Generated by Django 5.0.7 on 2024-07-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_restaurant_cart_item_restaurant_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant_cart_item',
            name='quantity',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
