# Generated by Django 5.0.7 on 2024-07-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_restaurant_cart_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant_cart_item',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
