# Generated by Django 5.0.7 on 2024-07-20 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cart',
            new_name='restaurant_cart',
        ),
    ]
