# Generated by Django 5.0.7 on 2024-07-20 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_rename_cart_order_restaurant_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='restaurant',
        ),
    ]
