# Generated by Django 5.0.7 on 2024-07-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_order_delivery_address_name_order_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_compelete',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='owner_approval',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
