# Generated by Django 5.0.7 on 2024-07-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_order_is_compelete_order_owner_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cvv2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='daynamic_password',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='payment',
            name='destination_card_number',
            field=models.CharField(blank=True, default='5894631129807582', max_length=16),
        ),
        migrations.AddField(
            model_name='payment',
            name='origin_card_number',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='payment',
            name='verification',
            field=models.CharField(default='', max_length=5),
        ),
    ]
