# Generated by Django 5.0.7 on 2024-07-27 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_alter_payment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cvv2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='daynamic_password',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='cart.order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='origin_card_number',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='payment',
            name='verification',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
