# Generated by Django 5.0.7 on 2024-07-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_alter_payment_cvv2_alter_payment_daynamic_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_complete',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
