# Generated by Django 5.0.7 on 2024-07-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_payment_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='expire_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
