# Generated by Django 5.0.7 on 2024-07-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_payment_expire_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant_cart',
            name='is_compelete',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
