# Generated by Django 5.0.7 on 2024-07-28 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_restaurant_cart_is_compelete'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='restaurant_cart',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='restaurant_cart_item',
            unique_together=set(),
        ),
    ]
