# Generated by Django 5.0.7 on 2024-08-17 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_owner_city_remove_owner_owner_address'),
        ('cart', '0019_alter_restaurant_cart_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChanceSpining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_discount', models.PositiveIntegerField()),
                ('amount_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('absurd', models.PositiveIntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.order')),
            ],
        ),
    ]
