# Generated by Django 5.0.7 on 2024-08-17 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_owner_city_remove_owner_owner_address'),
        ('cart', '0020_chancespining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chancespining',
            name='absurd',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='chancespining',
            name='amount_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='chancespining',
            name='customer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='account.customer'),
        ),
        migrations.AlterField(
            model_name='chancespining',
            name='order',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cart.order'),
        ),
        migrations.AlterField(
            model_name='chancespining',
            name='percentage_discount',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
