# Generated by Django 5.0.7 on 2024-08-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0022_alter_chancespining_absurd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price_after_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
